select
    bright_policy_id,
    policy_term,
    sum(earned_surplus) as earned_surplus,
    sum(premium_charge_off) as premium_charge_off,
    sum(fee_revenue) as fee_revenue,
    sum(inspection_fees) as inspection_fees,
    sum(program_administrator_fee_revenue) as program_administrator_fee_revenue,
    sum(direct_premiums_written) as direct_premiums_written,
    sum(change_in_unearned_premium_reserve) as change_in_unearned_premium_reserve,
    sum(state_tax_revenue) as state_tax_revenue,
    sum(state_tax_charge_off) as state_tax_charge_off,
    sum(figa_fee_revenue) as figa_fee_revenue,
    sum(figa_fee_charge_off) as figa_fee_charge_off,
    sum(refunds_payable) as refunds_payable,
    sum(empa_fee_payable) as empa_fee_payable,
    sum(unearned_premium_reserve) as unearned_premium_reserve,
    sum(premiums_received_in_advanced) as premiums_received_in_advanced,
    sum(unearned_surplus) as unearned_surplus,
    sum(state_tax_1_payable) as state_tax_1_payable,
    sum(state_tax_2_payable) as state_tax_2_payable,
    sum(state_tax_3_payable) as state_tax_3_payable,
    sum(premium_tax_deduction_payable) as premium_tax_deduction_payable,
    sum(fire_marshal_tax_deduction_payable) as fire_marshal_tax_deduction_payable,
    sum(premium_receivable) as premium_receivable,
    sum(deferred_installments) as deferred_installments,
    sum(cash) as cash,
    sum(unapplied_cash) as unapplied_cash,
    sum(state_tax_receivable) as state_tax_receivable,
    sum(figa_fee_receivable) as figa_fee_receivable,
    sum(suspense_account) as suspense_account,
    sum(state_tax_1_receivable) as state_tax_1_receivable,
    sum(state_tax_2_receivable) as state_tax_2_receivable,
    sum(state_tax_3_receivable) as state_tax_3_receivable,
    sum(state_tax_1_charge_off) as state_tax_1_charge_off,
    sum(state_tax_2_charge_off) as state_tax_2_charge_off,
    sum(state_tax_3_charge_off) as state_tax_3_charge_off,
    sum(unassigned_surplus) as unassigned_surplus
from {{ ref("fact_accounting_ledger_transactions_gold") }}
group by bright_policy_id, policy_term
